### ISSUE TITLE
Centralised .stagecoach file under version control

### ISSUE THREAD

**Issue by omnikron** [omnikron/stagecoach#77]
Instead of each developer having a local .stagecoach file it could be better to have a single .stagecoach file checked into version control.  We could then easily see which branch belongs to who, which branches can be deleted, etc.  This would then work with stagecoach --list to show all branches created in stagecoach and who they belong to and stagecoach --tidy to remove all branches which have been fully merged into master.

Each person could just have a segment of the file using their git user name, eg:

```
omnikron:
    test_branch_1:
        redmine_issue: 2422
        github_issue: 22
elsherif:
    test_branch_2:
        redmine_issue: 2423
        github_issue: 21
```
